language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - rbx-head
  - 2.1.0
gemfile:
  - Gemfile
  - gemfiles/rails-3.0.gemfile
  - gemfiles/rails-3.1.gemfile
  - gemfiles/rails-3.2.gemfile
