language: ruby
cache: bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  # - ruby-head
  # - jruby-19mode
  # - jruby-head
  # - rbx-19mode
  # - rbx-head

# matrix:
  # fast_finish: true

gemfile:
  - gemfiles/activerecord_2.3.gemfile
  - gemfiles/activerecord_3.0.gemfile
  - gemfiles/activerecord_3.1.gemfile
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.0.gemfile
