language: ruby
cache: bundler
bundler_args: --without development
sudo: false

rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby
  - rbx

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby
    - rvm: rbx

gemfile:
  - gemfiles/activerecord_2.3.gemfile
  - gemfiles/activerecord_3.0.gemfile
  - gemfiles/activerecord_3.1.gemfile
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
