language: ruby
cache: bundler
# bundler_args: --path=vendor/bundle/activerecord_$AR_VERSION --gemfile=gemfiles/activerecord_$AR_VERSION.gemfile --without development
bundler_args: --without development

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
  - rbx

matrix:
  # fast_finish: true
  allow_failures:
    - rvm: jruby
    - rvm: rbx

# gemfile:
#   - gemfiles/activerecord_2.3.gemfile
#   - gemfiles/activerecord_3.0.gemfile
#   - gemfiles/activerecord_3.1.gemfile
#   - gemfiles/activerecord_3.2.gemfile
#   - gemfiles/activerecord_4.0.gemfile

env:
  matrix:
    - AR_VERSION=2.3
    - AR_VERSION=3.0
    - AR_VERSION=3.1
    - AR_VERSION=3.2
    - AR_VERSION=4.0
